server.port=${PORT:8080}
spring.application.name=AiServer
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.timeline-model=gpt-4o-mini

