#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill for Render deployment.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-AiServer/.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  브라우저를 보면서 안내에 따라 진행해 주세요.\n' "$DIM"
  printf '  언제든지 Ctrl-C로 중단하고 다시 실행할 수 있습니다.%s\n\n' "$RESET"
  pause "시작할 준비가 되셨으면 Enter를 눌러주세요"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ 브라우저 열기:%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "브라우저를 열지 못했습니다. 직접 접속해 주세요: $url"; fi
  } >/dev/null 2>&1 || warn "브라우저를 열지 못했습니다. 직접 접속해 주세요: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '\n  %s%s%s ' "$DIM" "${1:-계속하려면 Enter를 누르세요}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter: 기존값 유지]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter: 기존값 유지]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  mkdir -p "$(dirname "$ENV_FILE")"
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ 저장됨%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Render 무료 배포 설정 완료!%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "로컬 환경변수 파일에 저장된 값 ($ENV_FILE): ${WRITTEN_ENV[*]}"
  if [[ -n "${RENDER_APP_URL:-}" ]]; then
    printf '\n  %s배포된 서버 주소:%s %s\n' "$BOLD" "$RESET" "$RENDER_APP_URL"
    printf '  %sSwagger UI:%s %s/swagger-ui/index.html\n' "$BOLD" "$RESET" "$RENDER_APP_URL"
  fi
  printf '\n  %s참고: Render 무료 티어는 약 15분간 요청이 없으면 서버가 절전(Sleep) 모드로 전환됩니다.%s\n' "$DIM" "$RESET"
  printf '  %s이후 첫 요청 시 깨어나는 데 약 30~50초 소요될 수 있습니다.%s\n\n' "$DIM" "$RESET"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Render (무료 티어) AiServer 배포 마법사"

# ── Stage 1: Render 로그인 ───────────────────────────────────────────────
stage "Render 로그인 / 회원가입"
say "Render 대시보드로 이동합니다. GitHub 계정으로 로그인해 주세요."
open_url "https://dashboard.render.com/"
step "Render 대시보드에 정상적으로 로그인되었는지 확인합니다."
pause "로그인이 완료되었으면 Enter를 눌러주세요."

# ── Stage 2: GitHub 레포지토리 연결 ──────────────────────────────────────
stage "새 Web Service 생성 및 레포지토리 선택"
say "새로운 Web Service를 생성하는 화면을 엽니다."
open_url "https://dashboard.render.com/select-repo?type=web"
step "'Connect a repository' 목록에서 현재 프로젝트(Lionbackend)를 선택(Connect)합니다."
note "목록에 레포지토리가 보이지 않는다면 'Configure access'를 눌러 권한을 허용해 주세요."
pause "레포지토리 연결(Connect) 버튼을 누른 후 Enter를 눌러주세요."

# ── Stage 3: 빌드 및 디렉토리 설정 ───────────────────────────────────────
stage "Web Service 옵션 및 Docker 환경 설정"
say "AiServer는 Dockerfile을 통해 무료 인스턴스에 배포됩니다. 아래 항목들을 입력/선택해 주세요:"
step "1. Name: lion-ai-server (또는 원하는 서비스 이름)"
step "2. Region: Singapore 또는 가장 가까운 리전 선택"
step "3. Root Directory: AiServer (대소문자 주의)"
step "4. Language / Runtime: Docker 선택 (Dockerfile 자동 감지)"
step "5. Instance Type: 'Free' ($0/month) 선택"
pause "설정을 입력하셨으면 Enter를 눌러주세요."

# ── Stage 4: 환경 변수(Environment Variables) 등록 ──────────────────────
stage "OpenAI API 키 설정"
say "AiServer 실행에 필요한 OPENAI_API_KEY를 설정합니다."
ask_secret OPENAI_API_KEY "OPENAI_API_KEY를 입력(또는 붙여넣기)해 주세요:"
if [[ -n "$OPENAI_API_KEY" ]]; then
  write_env OPENAI_API_KEY "$OPENAI_API_KEY"
fi

step "Render 설정 페이지 하단의 'Environment Variables' 섹션으로 이동합니다."
step "Key: OPENAI_API_KEY"
step "Value: 방금 입력한 OpenAI API 키 값을 붙여넣습니다."
pause "Render 대시보드에 환경 변수를 입력하셨으면 Enter를 눌러주세요."

# ── Stage 5: 배포 시작 및 URL 확인 ───────────────────────────────────────
stage "배포 시작 및 서비스 확인"
step "페이지 하단의 'Create Web Service' 또는 'Deploy' 버튼을 클릭합니다."
say "Docker 빌드 및 배포가 진행됩니다 (초기 빌드에는 3~5분 정도 소요될 수 있습니다)."
step "대시보드 상단에 생성된 서비스 URL (예: https://lion-ai-server.onrender.com)을 복사해 주세요."
ask RENDER_APP_URL "생성된 서비스 URL을 입력해 주세요 (Enter로 건너뛰기 가능):"

if [[ -n "$RENDER_APP_URL" ]]; then
  RENDER_APP_URL="${RENDER_APP_URL%/}"
  if confirm "브라우저에서 Swagger UI를 열어 정상 작동을 확인할까요?"; then
    open_url "${RENDER_APP_URL}/swagger-ui/index.html"
  fi
fi

# ──────────────────────────────────────────────────────────────────────────

finish
